# Generated by Django 5.1.5 on 2025-07-02 18:08

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ADM', 'Administration'), ('COM', 'Communication'), ('MUL', 'Multimedia'), ('ACC', 'Accounts'), ('EDT', 'Editorial')], max_length=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('am_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('pm_start_time', models.TimeField(default=datetime.time(14, 0))),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('session', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbnqrify.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date', 'session')},
            },
        ),
    ]
