# Generated by Django 5.2.3 on 2025-12-04 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbnqrify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ADM', 'Administration'), ('COM', 'Communication'), ('MUL', 'Multimedia'), ('ACC', 'Accounts'), ('EDT', 'Editorial'), ('Stf', 'Staff')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pm_start_time',
            field=models.TimeField(default=datetime.time(13, 30)),
        ),
    ]
